# Generated by Django 4.2.10 on 2024-02-27 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Modification Date')),
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('authors', models.CharField(max_length=255, verbose_name='Authors')),
                ('volume', models.CharField(blank=True, max_length=255, null=True, verbose_name='Volume')),
                ('series', models.CharField(blank=True, max_length=255, null=True, verbose_name='Series')),
                ('periodical', models.CharField(blank=True, max_length=255, null=True, verbose_name='Periodical')),
                ('publisher', models.CharField(blank=True, max_length=255, null=True, verbose_name='Publisher')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='City')),
                ('year', models.CharField(blank=True, max_length=255, null=True, verbose_name='Year')),
                ('edition', models.CharField(blank=True, max_length=255, null=True, verbose_name='Edition')),
                ('pages', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pages')),
                ('isbn', models.CharField(blank=True, max_length=255, null=True, verbose_name='ISBN')),
                ('time_added', models.CharField(blank=True, max_length=255, null=True, verbose_name='Time Added')),
                (
                'time_modified', models.CharField(blank=True, max_length=255, null=True, verbose_name='Time Modified')),
                ('library', models.CharField(blank=True, max_length=255, null=True, verbose_name='Library')),
                (
                'library_issue', models.CharField(blank=True, max_length=255, null=True, verbose_name='Library Issue')),
                ('size', models.CharField(blank=True, max_length=255, null=True, verbose_name='Size')),
                ('extension', models.CharField(blank=True, max_length=255, null=True, verbose_name='Extension')),
                ('topic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Topic')),
                ('tags', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tags')),
                ('issn', models.CharField(blank=True, max_length=255, null=True, verbose_name='ISSN')),
                ('udc', models.CharField(blank=True, max_length=255, null=True, verbose_name='UDC')),
                ('lbc', models.CharField(blank=True, max_length=255, null=True, verbose_name='LBC')),
                ('lcc', models.CharField(blank=True, max_length=255, null=True, verbose_name='LCC')),
                ('ddc', models.CharField(blank=True, max_length=255, null=True, verbose_name='DDC')),
                ('doi', models.CharField(blank=True, max_length=255, null=True, verbose_name='DOI')),
                ('open_library_id',
                 models.CharField(blank=True, max_length=255, null=True, verbose_name='OpenLibrary ID')),
                ('google_books', models.CharField(blank=True, max_length=255, null=True, verbose_name='Google Books')),
                ('asin', models.CharField(blank=True, max_length=255, null=True, verbose_name='ASIN')),
                ('dpi', models.CharField(blank=True, max_length=255, null=True, verbose_name='DPI')),
                ('ocr', models.CharField(blank=True, max_length=255, null=True, verbose_name='OCR')),
                ('bookmarked', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bookmarked')),
                ('scanned', models.CharField(blank=True, max_length=255, null=True, verbose_name='Scanned')),
                ('orientation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Orientation')),
                ('paginated', models.CharField(blank=True, max_length=255, null=True, verbose_name='Paginated')),
                ('color', models.CharField(blank=True, max_length=255, null=True, verbose_name='Color')),
                ('clean', models.CharField(blank=True, max_length=255, null=True, verbose_name='Clean')),
                ('image_save_url', models.URLField(blank=True, null=True, verbose_name='Image Save URL')),
                ('image_download_url', models.URLField(blank=True, null=True, verbose_name='Image Download URL')),
                ('file_save_url', models.URLField(blank=True, null=True, verbose_name='File Save URL')),
                ('file_download_url', models.URLField(blank=True, null=True, verbose_name='File Download URL')),
                ('is_downloaded', models.BooleanField(default=False, verbose_name='Is Downloaded')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('keyword', models.CharField(max_length=255, verbose_name='Keyword')),
            ],
            options={
                'verbose_name': 'Keyword',
                'verbose_name_plural': 'Keywords',
            },
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_results',
                                           to='scraper.book')),
                ('keyword',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_results',
                                   to='scraper.keyword')),
            ],
            options={
                'verbose_name': 'Search Result',
                'verbose_name_plural': 'Search Results',
            },
        ),
    ]
