# Generated by Django 4.2.10 on 2024-02-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Language'),
        ),
    ]
